name: Efficax
version: 1.16.4
main: com.github.metater.efficax.Efficax
author: Metater
commands:
  diamonds:
    description: Gives you diamonds
    usage: /diamonds <number of items>
    permission: efficax.diamonds
  gui:
    description: Opens a GUI inventory, for learning
    usage: /gui
    permission: efficax.gui